version: "2"

services:
  pixelcloud-nginx-proxy:
    image: pixelfordinner/nginx
    container_name: pixelcloud-nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./volumes/conf.d:/etc/nginx/conf.d"
      - "./volumes/vhost.d:/etc/nginx/vhost.d"
      - "./volumes/certs:/etc/nginx/certs:ro"
      - "/usr/share/nginx/html"
    networks:
      - proxy-tier
  pixelcloud-docker-gen:
    image: jwilder/docker-gen
    container_name: pixelcloud-docker_gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./data/templates:/etc/docker-gen/templates:ro"
    volumes_from:
      - pixelcloud-nginx-proxy
    entrypoint: /usr/local/bin/docker-gen -notify-sighup pixelcloud-nginx_proxy -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  pixelcloud-lets-encrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: pixelcloud-lets_encrypt
    volumes_from:
      - pixelcloud-nginx-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=pixelcloud-docker_gen
      # - ACME_CA_URI=https://acme-staging.api.letsencrypt.org/directory
networks:
  proxy-tier:
    external:
      name: nginx-proxy
